version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: mapeamento-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mapeamento-ambiental
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: ./mapeamento-api
    container_name: mapeamento-api
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:docker@postgres:5432/mapeamento-ambiental
      NODE_ENV: production
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npm run start:prod"

  app:
    build:
      context: ./mapeamento-app
    container_name: mapeamento-app
    restart: always
    environment:
      NEXT_PUBLIC_API_URL: http://api:3333
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  pgdata:
